### ISSUE TITLE
move maps to subfolder

### ISSUE THREAD

**Issue by heroesiiifan** [vcmi-mods/dydzios-map-pack#1]
Because VCMI 1.4 supports it now: Looks much cleaner if all map packs are in a subfolder (the others are already in subfolder).

![grafik](https://github.com/vcmi-mods/dydzios-map-pack/assets/77574150/ecd5b953-0429-4be5-9090-a856f2b7e6be)

@misiokles @dydzio0614

**Comment by misiokles** [comment]
Done. Thanks! I dodn't know about it :)

**Comment by misiokles** [comment]
But I didn's search for duplicates. Too many files for me :(
